---
language: ruby
rvm:
  - 2.0.0

cache:
- bundler
- apt

env:
  - FACTER_VER='<= 1.7.2' SCRIPT='script/test'
  - FACTER_VER='<= 1.7.2' SCRIPT='script/mintest'
  - FACTER_VER='~> 2.0' SCRIPT='script/test'
  - FACTER_VER='~> 2.0' SCRIPT='script/mintest'
  - FACTER_VER='bisect' SCRIPT='script/bisect'

matrix:
  fast_finish: false

before_install:
  - date --rfc-3339=seconds --utc
  - gem --version

before_script:
  - git config user.email 'nobody@localhost.invalid'
  - git config user.name  'travis-ci'

script:
  - $SCRIPT

after_script:
  - date --rfc-3339=seconds --utc
