#!/bin/bash
set -e
source $(dirname $0)/config
pushd $repo_root 2> /dev/null

git remote show upstream &> /dev/null || smitty git remote add upstream $upstream
smitty git submodule update --init --recursive
$repo_root/script/bundle
