#!/bin/bash

set -e

function err() {
  echo "[ERROR] $1" >&2
  exit 1
}

function smitty() {
  echo; echo
  echo "[INFO] $@"
  $@
}

git remote show upstream &> /dev/null || smitty git remote add upstream git@github.com:ISEexchange/win32ole_vs_facter.git
smitty bundle update 2> /dev/null || smitty bundle install --path=~/.bundle
