#!/bin/bash

set -e

function err() {
  echo "[ERROR] $1" >&2
  exit 1
}

function smitty() {
  echo; echo
  echo "[INFO] $@"
  $@
}

bundle_dir="~/.bundle"

git remote show upstream &> /dev/null || smitty git remote add upstream git@github.com:ISEexchange/win32ole_vs_facter.git
smitty git submodule update --init --recursive
smitty rm -fr $bundle_dir
smitty rm -fr Gemfile.lock
smitty bundle update 2> /dev/null || smitty bundle install --path=$bundle_dir
